#!/bin/bash
yum update -y 
yum install httpd -y
echo "<html><body><center><h1>Hello IIHT. Here is my web page!</h1></center></body></html>" > /var/www/html/index.html
systemctl start httpd
systemctl enable httpd
updated
updated again
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDHAxMJ4Z0QugwiPODXcW4RFcvG521xF2KVydghOni7S bindu.ediga6@gmail.com

